#!/bin/bash
MESSAGE=$(cat $1) 
COMMITFORMAT="^(feat|fix|docs|style|refactor|test|chore|perf|other)(\((.)\))?: (.)[a-zA-Z\s]*+$"

if ! [[ "$MESSAGE" =~ $COMMITFORMAT ]]; then
  echo "Your commit was rejected because don't follow of pattern" 
  echo ""
  echo "Please, utilize the below example"
  echo "feat: your comment about task"
  echo ""
  exit 1
fi